all:
    children:
        cloud:
            hosts:
                test1:
                    ansible_host: 20.10.10.161
                    ansible_user: ubuntu
                    ansible_port: 22
                test2:
                    ansible_host: 20.10.10.165
                    ansible_user: ubuntu
                    ansible_port: 22
                test3:
                    ansible_host: 20.10.10.74
                    ansible_user: ubuntu
                    ansible_port: 22
                dev:
                    ansible_host: 20.10.10.149
                    ansible_user: ubuntu
                    ansible_port: 22

        baremetal:
            hosts:
                dense:
                    ansible_host: 192.168.100.10
                    ansible_user: dense
                    ansible_port: 22
                    ansible_become_pass: ' ' 
